# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraficasDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GraficasDialog(object):
    def setupUi(self, GraficasDialog):
        GraficasDialog.setObjectName("GraficasDialog")
        GraficasDialog.resize(428, 354)
        self.le_datos = QtWidgets.QLineEdit(GraficasDialog)
        self.le_datos.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.le_datos.setObjectName("le_datos")
        self.lbl_datos = QtWidgets.QLabel(GraficasDialog)
        self.lbl_datos.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.lbl_datos.setObjectName("lbl_datos")
        self.le_titulo = QtWidgets.QLineEdit(GraficasDialog)
        self.le_titulo.setGeometry(QtCore.QRect(10, 180, 113, 20))
        self.le_titulo.setObjectName("le_titulo")
        self.lbl_titulo = QtWidgets.QLabel(GraficasDialog)
        self.lbl_titulo.setGeometry(QtCore.QRect(10, 153, 121, 20))
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_x = QtWidgets.QLabel(GraficasDialog)
        self.lbl_x.setGeometry(QtCore.QRect(10, 206, 111, 20))
        self.lbl_x.setObjectName("lbl_x")
        self.lbl_y = QtWidgets.QLabel(GraficasDialog)
        self.lbl_y.setGeometry(QtCore.QRect(10, 260, 111, 20))
        self.lbl_y.setObjectName("lbl_y")
        self.le_x = QtWidgets.QLineEdit(GraficasDialog)
        self.le_x.setGeometry(QtCore.QRect(10, 230, 113, 20))
        self.le_x.setObjectName("le_x")
        self.le_y = QtWidgets.QLineEdit(GraficasDialog)
        self.le_y.setGeometry(QtCore.QRect(10, 290, 113, 20))
        self.le_y.setObjectName("le_y")
        self.guardar_dato = QtWidgets.QPushButton(GraficasDialog)
        self.guardar_dato.setGeometry(QtCore.QRect(10, 120, 111, 23))
        self.guardar_dato.setObjectName("guardar_dato")
        self.guardar_titulo = QtWidgets.QPushButton(GraficasDialog)
        self.guardar_titulo.setGeometry(QtCore.QRect(10, 320, 111, 23))
        self.guardar_titulo.setObjectName("guardar_titulo")
        self.lbl_seaborn = QtWidgets.QLabel(GraficasDialog)
        self.lbl_seaborn.setGeometry(QtCore.QRect(230, 60, 171, 16))
        self.lbl_seaborn.setObjectName("lbl_seaborn")
        self.lbl_mat = QtWidgets.QLabel(GraficasDialog)
        self.lbl_mat.setGeometry(QtCore.QRect(230, 150, 171, 16))
        self.lbl_mat.setObjectName("lbl_mat")
        self.s_linea = QtWidgets.QRadioButton(GraficasDialog)
        self.s_linea.setGeometry(QtCore.QRect(230, 90, 82, 17))
        self.s_linea.setObjectName("s_linea")
        self.s_barras = QtWidgets.QRadioButton(GraficasDialog)
        self.s_barras.setGeometry(QtCore.QRect(230, 120, 82, 17))
        self.s_barras.setObjectName("s_barras")
        self.m_linea = QtWidgets.QRadioButton(GraficasDialog)
        self.m_linea.setGeometry(QtCore.QRect(230, 180, 82, 17))
        self.m_linea.setObjectName("m_linea")
        self.m_pie = QtWidgets.QRadioButton(GraficasDialog)
        self.m_pie.setGeometry(QtCore.QRect(230, 210, 82, 17))
        self.m_pie.setObjectName("m_pie")
        self.m_barras = QtWidgets.QRadioButton(GraficasDialog)
        self.m_barras.setGeometry(QtCore.QRect(230, 240, 82, 17))
        self.m_barras.setObjectName("m_barras")
        self.genera_grafica = QtWidgets.QPushButton(GraficasDialog)
        self.genera_grafica.setGeometry(QtCore.QRect(230, 270, 111, 23))
        self.genera_grafica.setObjectName("genera_grafica")
        self.lbl_elemento = QtWidgets.QLabel(GraficasDialog)
        self.lbl_elemento.setGeometry(QtCore.QRect(10, 60, 121, 20))
        self.lbl_elemento.setObjectName("lbl_elemento")
        self.le_elemento = QtWidgets.QLineEdit(GraficasDialog)
        self.le_elemento.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.le_elemento.setObjectName("le_elemento")

        self.retranslateUi(GraficasDialog)
        QtCore.QMetaObject.connectSlotsByName(GraficasDialog)

    def retranslateUi(self, GraficasDialog):
        _translate = QtCore.QCoreApplication.translate
        GraficasDialog.setWindowTitle(_translate("GraficasDialog", "Generador de graficas"))
        self.lbl_datos.setText(_translate("GraficasDialog", "Introduce tu dato:"))
        self.lbl_titulo.setText(_translate("GraficasDialog", "Titulo de la grafica:"))
        self.lbl_x.setText(_translate("GraficasDialog", "Titulo del eje X:"))
        self.lbl_y.setText(_translate("GraficasDialog", "Titulo del eje Y:"))
        self.guardar_dato.setText(_translate("GraficasDialog", "Guardar dato"))
        self.guardar_titulo.setText(_translate("GraficasDialog", "Guardar titulos"))
        self.lbl_seaborn.setText(_translate("GraficasDialog", "Graficas con seaborn:"))
        self.lbl_mat.setText(_translate("GraficasDialog", "Graficas con MatPlotLib:"))
        self.s_linea.setText(_translate("GraficasDialog", "Linea"))
        self.s_barras.setText(_translate("GraficasDialog", "Barras"))
        self.m_linea.setText(_translate("GraficasDialog", "Linea"))
        self.m_pie.setText(_translate("GraficasDialog", "Pie"))
        self.m_barras.setText(_translate("GraficasDialog", "Barras"))
        self.genera_grafica.setText(_translate("GraficasDialog", "Generar grafica"))
        self.lbl_elemento.setText(_translate("GraficasDialog", "Introduce tu elemento:"))
